---
- name: Install ntp
  yum:
    name=ntp
    state=latest
  tags:
  - packages

- name: Enable ntpd service
  service:
    name=ntpd
    enabled=yes

- name: Install ntp.conf
  template:
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    mode=0644
  notify:
    - restart ntp

