---
- name: Install ntp
  apt:
          name=ntp
          state=latest
  tags:
  - packages

- name: Enable ntp service
  service: 
          name=ntp
          enabled=yes

- name: Install ntp.conf
  template: 
          src=ntp.conf.j2 
          dest=/etc/ntp.conf 
          mode=0644
  notify: restart ntp
